
export const STORE_MODIFIER_ACTION = 'STORE_MODIFIER_ACTION';
export const STORE_SELECTED_ITEM_MODIFIERS_ACTION = 'STORE_SELECTED_ITEM_MODIFIERS_ACTION';
export const TRACK_MODIFIERS_MODIFIERS_ACTION = 'TRACK_MODIFIERS_MODIFIERS_ACTION';

export const STORE_MODIFIERS = (modifiers) => ({type:STORE_MODIFIER_ACTION,payload:modifiers});
export const STORE_SELECTED_ITEM_MODIFIERS = (item) => ({type:STORE_SELECTED_ITEM_MODIFIERS_ACTION,payload:item});
export const TRACK_MODIFIERS_MODIFIERS = (item) => ({type:TRACK_MODIFIERS_MODIFIERS_ACTION,payload:item});
